### ISSUE TITLE
[FEATURE] Store chart settings as part of the saved layout

### ISSUE THREAD

**Issue by ianmuchyri** [absmach/magistrala-ui#139]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Is your feature request related to a problem? Please describe.

We currently do not store any chart data alongside the layout saved

### Describe the feature you are requesting, as well as the possible use case(s) for it.

We should be able to store chart settings alongside the layout such that when the dashboard is received, the chart settings are also loaded to the respective chart

### Indicate the importance of this feature to you.

- [X] Must-have
- [ ] Should-have
- [ ] Nice-to-have

**Comment by dborovcanin** [comment]
Chart data in this case are metadata about a particular chart such as appearance details and filter included for data stream: start time for time-series data, pooling period for fetching data, grouping criteria, and so on.

**Comment by ianmuchyri** [comment]
Also, check if we can improve how we store the layout, reduce the data we store, store in a better format, etc.
