### ISSUE TITLE
[FEATURE] Streaming of messages using WebSockets

### ISSUE THREAD

**Issue by ianmuchyri** [absmach/magistrala-ui#20]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Is your feature request related to a problem? Please describe.

No

### Describe the feature you are requesting, as well as the possible use case(s) for it.

We should provision for streaming of messages as they are sent on a channel using WebSockets

### Indicate the importance of this feature to you.

- [ ] Must-have
- [ ] Should-have
- [X] Nice-to-have

**Comment by dborovcanin** [comment]
We don't need it, since we can have pooling set to short periods. Closing.
