### ISSUE TITLE
[BUG] Super admins should not be visible in Users screen

### ISSUE THREAD

**Issue by dborovcanin** [absmach/magistrala-ui#38]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What were you trying to achieve?

When using UI for a particular domain, in `users` section I see super admins.

### What are the expected results?

I expect to see only users who accepted invitations or who are explicitly added by super admins.

### What are the received results?

I see all the users who have access.

### Steps To Reproduce

Run Magistrala's latest Docker compose, run UI, register user, login, create a domain, log in with domain, and go to `users` screen.

### In what environment did you encounter the issue?

Docker V24.0.7, Compose 2.23.3, the latest version of core services, and the latest version of UI.

### Additional information you deem important
![image](https://github.com/absmach/magistrala-ui/assets/17817225/2cd53e15-e591-4caa-b2a2-9ba3a6636637)

**Comment by ianmuchyri** [comment]
This issue was solved on the Magistrala end. A user is no longer able to view a user with the role of admin
