### ISSUE TITLE
[BUG] Channel name does not pass validation check

### ISSUE THREAD

**Issue by dborovcanin** [absmach/magistrala-ui#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What were you trying to achieve?

I'm trying to create a Channel.

### What are the expected results?

I expect to succeed once I enter valid data into the form.

### What are the received results?

Validation assumes the Name is empty even if it is not.

### Steps To Reproduce

1. Run Magistrala's latest Docker compose
2. Run UI
3. Register user
4. Login
5. Create a domain
6. Log in with the domain
7. Go to Channels
8. Try adding a new channel

### In what environment did you encounter the issue?

Docker V24.0.7, Compose 2.23.3, the latest version of core services, and the latest version of UI.

### Additional information you deem important

![image](https://github.com/absmach/magistrala-ui/assets/17817225/50a8817c-1fe0-45d1-ad48-62b81c2ee5bd)

**Comment by Vadim-vg** [comment]
With `Add Thing` there is the same problem, if necessary I can add a new error.

![image](https://github.com/absmach/magistrala-ui/assets/49375747/63b8f5e5-785e-4343-b65b-0c913ad9c8de)
