### ISSUE TITLE
[BUG] Failure to decode channel with `parentID`

### ISSUE THREAD

**Issue by rodneyosodo** [absmach/magistrala-ui#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What were you trying to achieve?

View a channel that has a `parentID`.

### What are the expected results?

To be able to view the channel and possibly the `parentID`

### What are the received results?

![image-2](https://github.com/absmach/magistrala-ui/assets/28790446/0d736ac6-83de-4471-aae4-17e407afe1b2)

```bash
{"level":"info","message":"Method list_channels took 9.069263ms to complete without errors.","ts":"2023-12-18T09:39:44.955237986Z"}
{"level":"info","message":"Method get_entities took 5.670268ms to complete without errors.","ts":"2023-12-18T09:39:45.02150105Z"}
{"level":"warn","message":"Method view_channel for channel 5a281255-536d-4263-bfb1-59882d1aae6c took 2.443387ms to complete with error: unexpected end of JSON input : failed to retrieve entity.","ts":"2023-12-18T09:39:46.239980389Z"}
{"level":"info","message":"Method ErrorPage took 4.183833ms to complete without errors.","ts":"2023-12-18T09:39:46.250487103Z"}
```

### Steps To Reproduce

1. Login in as super user
2. Create channel 1
3. Create channel 2 with channel 1 as parentID
4. Try to view channel2

### In what environment did you encounter the issue?

Git commit - https://github.com/absmach/magistrala-ui/commit/b40e56212d69fea09fb68c32e1006b2ff80de63c
Docker Compose version 2.23.3
Docker version

> 	Client:
> 	 Version:           24.0.7
> 	 API version:       1.43
> 	 OS/Arch:           linux/amd64
> 	
> 	Server:
> 	 Engine:
> 	  Version:          24.0.7
> 	  API version:      1.43 (minimum version 1.12)

**Comment by ianmuchyri** [comment]
this is based on an issue with Magistrala https://github.com/absmach/magistrala/issues/187
