### ISSUE TITLE
[BUG] Superfluous response header writes

### ISSUE THREAD

**Issue by dborovcanin** [absmach/magistrala-ui#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What were you trying to achieve?

I'm listing Things by Channel (with Auth error).

### What are the expected results?

I expect to receive the error page.

### What are the received results?

I received the correct result, but I also see the following warning:
```
2023/12/25 15:06:09 http: superfluous response.WriteHeader call from github.com/absmach/magistrala-ui/ui/api.encodeError (transport.go:2361)
```

### Steps To Reproduce

Login in with the domain, create the channel, and click on the `connect` button.

### In what environment did you encounter the issue?

Latest images of Magistrala and UI, with Docker 24.0.7 and Compose version 2.23.3.

**Comment by ianmuchyri** [comment]
I am not able to reproduce these results.
![image](https://github.com/absmach/magistrala-ui/assets/100555904/28d3571c-fed2-4237-bde3-2bb7c11b455f)
