### ISSUE TITLE
[BUG] - Adding channel with the parent fails silently

### ISSUE THREAD

**Issue by dborovcanin** [absmach/magistrala-ui#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What were you trying to achieve?

I am trying to add a new Channel with a specified parent.

### What are the expected results?

I expect the operation to succeed.

### What are the received results?

No visible results. The channel is created successfully (and correctly), but I can't see it on the UI.

### Steps To Reproduce

Use the latest Magistrala and UI docker images, with Docker v24.0.0. Create a Channel and try to create another one with the previous Channel as a parent.

### In what environment did you encounter the issue?

The latest (main branch) versions of MG and MG-UI running in Docker v24.0.0.

**Comment by ianmuchyri** [comment]
This issue had been created here https://github.com/absmach/magistrala-ui/issues/44
