### ISSUE TITLE
Create a layout for dashboards

### ISSUE THREAD

**Issue by dborovcanin** [absmach/magistrala-ui#92]
Add a canvas that supports a grid to place widgets on the dashboard.

**Comment by ianmuchyri** [comment]
Some of the subtasks for this issue include:

- [ ] Implement canvas for placing widgets on the dashboard.
- [ ] Create a sidebar with the widgets that allows a user to select which widget they would like to add to the canvas.
- [ ] Be able to export the created dashboard in JSON format for saving to the database or downloading by the user.
- [ ] Facilitate the creation of multiple dashboards.
- [ ] Be able to enable and disable the editing of the layout (A user should be able to enter edit mode and edit the canvas. When outside the edit mode, the widgets should be static)
- [ ] Facilitate resizing of the widgets.
