### ISSUE TITLE
Add storage for dashboards

### ISSUE THREAD

**Issue by dborovcanin** [absmach/magistrala-ui#94]

**Comment by ianmuchyri** [comment]
- [ ] Based on this https://github.com/absmach/magistrala-ui/issues/81#issuecomment-1898220082, design and implement a suitable database to be used for storage of the dashboards created by a user in the UI
- [ ] The dashboards should be retrieved based on the user logged in. This should facilitate authorization of the user requesting to fetch the data
- [ ] Be able to carry out CRUD operations on the data stored.

**Comment by ianmuchyri** [comment]
solved by https://github.com/absmach/magistrala-ui/pull/104
