### ISSUE TITLE
Update sources (Readers) to work with widgets

### ISSUE THREAD

**Issue by dborovcanin** [absmach/magistrala-ui#96]

**Comment by dborovcanin** [comment]
Related to https://github.com/absmach/magistrala/issues/1966.

**Comment by ianmuchyri** [comment]
Some of the items we need to focus on include:

- [ ] Determining the dataset length to avoid fetching large data for charts
- [ ] Data aggregation?
- [ ] Data fetch interval (e.g if data is fetched for 1 day, should the interval between each data be 1hr, 1minute, 2hrs e.t.c). This will also be related to the data aggregation
- [ ] Polling of database
- [ ] Web socket connection for widgets that display realtime data e.g guages.

**Comment by 1998-felix** [comment]
## Type of chart
 - Analogue gauge
 - Pressure gauge
 - Temperature
## Type of data required
> Realtime data

## Potential modifications
1. Query data by thing Id and name of sensor paramter
2. Upgrade protocol to ws for real time data streaming or
3. Use async time intervals on the frontend.

## Type of chart
 - Time series line chart
 - Range chart
 - Area line chart
 - Dynamic chart

## Type of data required
>Y axis data:  sensor value
>X axis data: time data

## Potential modifications
1. Query data by thing ID, name of sensor parameter, start period, end period

## Type of chart
 - Pi chart
 - Donut chart
## Type of data required
Aggregated data from different publishers on a channel for a single named parameter

## Potential modification
Query data by thing ID, name of sensor parameter, start period, end period and aggregate 

## Notes
The return type is maintained as is from sdk.ReadMessages

**Comment by dborovcanin** [comment]
Currently, we will focus only on data filtering (and aggregation if necessary) to enable charts to work; https://github.com/absmach/magistrala/issues/1966 is a lower priority and will be added in the next release.
